modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/PrickleMC/issues"

[[mods]]
modId = "prickle"
version = "26.2.0.0"
displayName = "PrickleMC"
updateJSONURL = "https://updates.blamejared.com/get?n=prickle&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/prickle"
logoFile = "logo_prickle.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Bringing Prickle, the JSON based configuration file format to Minecraft."

[[mixins]]
config = "prickle.common.mixins.json"

[[mixins]]
config = "prickle.neoforge.mixins.json"

[[dependencies.prickle]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.prickle]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.8-beta,)"
ordering = "NONE"
side = "BOTH"

